USE QLBH_1
GO

DROP PROC IF EXISTS USP_GetStores
GO

CREATE 
--ALTER 
PROC USP_GetStores
AS
BEGIN TRAN
	SELECT M.TENMON, M.MIEUTA, M.GIA 
	FROM MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON
COMMIT TRAN
GO

DROP PROC IF EXISTS USP_GetDisks
GO

CREATE 
--ALTER 
PROC USP_GetDisks
AS
BEGIN TRAN
	SELECT C.TENQUAN, M.TENMON, M.MIEUTA, M.GIA 
	FROM (MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON) JOIN CUAHANG C ON C.MACUAHANG = P.MACUAHANG
COMMIT TRAN
GO

--EXEC USP_GetDisks

DROP PROC IF EXISTS USP_GetStoreByID
GO

CREATE 
--ALTER 
PROC USP_GetStoreByID
	@ID CHAR(15)
AS
BEGIN TRAN
	IF NOT EXISTS (SELECT MACUAHANG FROM CUAHANG WHERE TRIM(MACUAHANG) = TRIM(@ID))
		BEGIN
			SELECT 'MACUAHANG IS NOT EXIST' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	SELECT M.TENMON, M.MIEUTA, M.GIA 
	FROM MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON WHERE TRIM(P.MACUAHANG) = TRIM(@ID)
COMMIT TRAN
GO

--EXEC USP_GetStoreByID @ID = 'CH853CAQ'

DROP PROC IF EXISTS USP_GetStoreByName
GO

CREATE 
--ALTER 
PROC USP_GetStoreByName
	@Name NCHAR(35)
AS
BEGIN TRAN
	IF NOT EXISTS (SELECT TENQUAN FROM CUAHANG WHERE TRIM(TENQUAN) = TRIM(@Name))
		BEGIN
			SELECT 'TENQUAN IS NOT EXIST' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0;
		END

	SELECT M.TENMON, M.MIEUTA, M.GIA 
	FROM (MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON) JOIN CUAHANG C ON C.MACUAHANG = P.MACUAHANG
	WHERE TRIM(C.TENQUAN) = TRIM(@Name)
COMMIT TRAN
GO

--EXEC USP_GetStoreByName @Name = 'Emanan Direct'

DROP PROC IF EXISTS USP_GetDiskByID
GO

CREATE 
--ALTER 
PROC USP_GetDiskByID
	@ID NCHAR(80)
AS
BEGIN TRAN
	IF NOT EXISTS (SELECT TENMON FROM MONAN WHERE TRIM(TENMON) = TRIM(@ID))
		BEGIN
			SELECT 'TENMON IS NOT EXIST' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	SELECT C.TENQUAN, M.TENMON, M.MIEUTA, M.GIA 
	FROM (MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON) JOIN CUAHANG C ON C.MACUAHANG = P.MACUAHANG 
	WHERE TRIM(M.TENMON) = TRIM(@ID) 
COMMIT TRAN
GO

--EXEC USP_GetDiskByID @ID = 'Bánh AAA'