USE QLBH
GO

DROP PROC IF EXISTS USP_GetStores
GO

CREATE 
--ALTER 
PROC USP_GetStores
AS
BEGIN TRAN
	SELECT M.TENMON, M.MIEUTA, M.GIA 
	FROM MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON
COMMIT TRAN
GO

DROP PROC IF EXISTS USP_GetDisks
GO

CREATE 
--ALTER 
PROC USP_GetDisks
AS
BEGIN TRAN
	SELECT C.TENQUAN, M.TENMON, M.MIEUTA, M.GIA 
	FROM (MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON) JOIN CUAHANG C ON C.MACUAHANG = P.MACUAHANG
COMMIT TRAN
GO

--exec USP_GetDisks

DROP PROC IF EXISTS USP_GetStoreByID
GO

CREATE 
--ALTER 
PROC USP_GetStoreByID
	@ID CHAR(20)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT MACUAHANG FROM CUAHANG WHERE MACUAHANG = @ID)
		--OR NOT EXISTS (SELECT MACUAHANG FROM CUAHANG WHERE TENQUAN = @ID)
			BEGIN
				ROLLBACK TRAN
			END
	END TRY

	BEGIN CATCH
		PRINT N'CỬA HÀNG KHÔNG TỒN TẠI'
		ROLLBACK
	END CATCH

	SELECT M.TENMON, M.MIEUTA, M.GIA 
	FROM MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON WHERE P.MACUAHANG = @ID
COMMIT TRAN
GO

--EXEC USP_GetStoreByID @ID = 'ID001'

DROP PROC IF EXISTS USP_GetDiskByID
GO

CREATE 
--ALTER 
PROC USP_GetDiskByID
	@ID CHAR(20)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT TENMON FROM MONAN WHERE TENMON = @ID)
			BEGIN
				ROLLBACK TRAN
			END
	END TRY

	BEGIN CATCH
		PRINT N'MÓN ĂN KHÔNG TỒN TẠI'
		ROLLBACK
	END CATCH

	SELECT C.TENQUAN, M.TENMON, M.MIEUTA, M.GIA 
	FROM (MONAN M JOIN PHUCVU P ON M.TENMON = P.TENMON) JOIN CUAHANG C ON C.MACUAHANG = P.MACUAHANG 
	WHERE M.TENMON = @ID
COMMIT TRAN
GO

--EXEC USP_GetDiskByID @ID = 'Tetopentor'